### ISSUE TITLE
Dataset availability

### ISSUE THREAD

**Issue by Amnx404** [evo-biomech/replicAnt#3]
Hi, team, after going through your repo and paper page, I was unable to find any dataset with regards to ant's themselves(not the 3D models). Would it be possible to access it? Even some samples would work just fine, we want to understand the kind of data that was being used for evaluation and training.

**Comment by FabianPlum** [comment]
Hi @Amnx404,
We're excited to hear you are looking into replicAnt!
All datasets (both real and synthetically generated are available) are available for download via Zenodo:

Detection and tracking:
[https://zenodo.org/records/7849417](https://zenodo.org/records/7849417)

Pose estimation 
[https://zenodo.org/records/7849596](https://zenodo.org/records/7849596)

Semantic segmentation 
[https://zenodo.org/records/7849570](https://zenodo.org/records/7849570)

**Comment by Amnx404** [comment]
Thanks a lot. Amazing work! We are working on the detection of brown plant hopper pests in India. They are in extremely unpredictable environments. Sometimes they have mud on or sometimes occluded by some plant. Would love to hear any insights that you might have.

**Comment by FabianPlum** [comment]
Hi @Amnx404,
That sounds like a super interesting project and likely a great use case for replicAnt generated data! Could you elaborate a little more on what kind of information you want to extract and perhaps share some example footage?

In any case, it will likely be useful to make (or otherwise procure) a 3D model of your target species to be used with replicAnt.

All the best 
Fabi

**Comment by Amnx404** [comment]
We want to train a YOLO based object detection network for brown plant hopper. We are skeptical since the environment of these pests is very different and varied, not at all controlled. We want to train something like replicAnt in order make our models robust.
(for ref: https://universe.roboflow.com/new-workspace-aedre/brown-plant-hopper-adult/browse?queryText=&pageSize=50&startingIndex=0&browseQuery=true)

Below is a dataset screenshot of this pest. 
![CleanShot 2024-05-22 at 12 35 48@2x](https://github.com/evo-biomech/replicAnt/assets/91665648/5c876c87-5d5a-426d-b42b-5604c681106e)

**Comment by FabianPlum** [comment]
That's super interesting! I think this should be feasible.
@Amnx404 Do you have a means of producing a 3D model of the species you are interested in?

**Comment by FabianPlum** [comment]
Ah, sorry accidentally reopened the issue. Let's move this conversation to a new issue to keep things clean
